yarnPath: .yarn/releases/yarn-2.4.0.cjs

npmPublishRegistry: "https://peterlgerrard.pkgs.visualstudio.com/_packaging/Testing/npm/registry/"

packageExtensions:
  "@fullhuman/postcss-purgecss@*":
    dependencies:
      "postcss": "*"
