changesetBaseRefs:
  - "main"
  - "origin/main"

packageExtensions:
  "@fullhuman/postcss-purgecss@*":
    dependencies:
      postcss: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-2.4.0.cjs

npmPublishRegistry: https://pkgs.dev.azure.com/peterlgerrard/_packaging/Testing/npm/registry/
